// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPQQL5Ssdlhuowj1AAPhLMAcmHDsHu-0',
    appId: '1:1077071696056:web:0fe25cab1abe22ddc4644d',
    messagingSenderId: '1077071696056',
    projectId: 'employeedemoapp-48cb5',
    authDomain: 'employeedemoapp-48cb5.firebaseapp.com',
    storageBucket: 'employeedemoapp-48cb5.appspot.com',
    measurementId: 'G-TD665S42GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVpvv25t1dGBb9e0qrfliGW41bcePi88',
    appId: '1:1077071696056:android:abc538a71e2b4156c4644d',
    messagingSenderId: '1077071696056',
    projectId: 'employeedemoapp-48cb5',
    storageBucket: 'employeedemoapp-48cb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyIW1go60iLrYSkOtnnaOu5NFMimRYnPw',
    appId: '1:1077071696056:ios:bc50ba982f4ea476c4644d',
    messagingSenderId: '1077071696056',
    projectId: 'employeedemoapp-48cb5',
    storageBucket: 'employeedemoapp-48cb5.appspot.com',
    iosBundleId: 'com.mani.employeedemoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIW1go60iLrYSkOtnnaOu5NFMimRYnPw',
    appId: '1:1077071696056:ios:bc50ba982f4ea476c4644d',
    messagingSenderId: '1077071696056',
    projectId: 'employeedemoapp-48cb5',
    storageBucket: 'employeedemoapp-48cb5.appspot.com',
    iosBundleId: 'com.mani.employeedemoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPQQL5Ssdlhuowj1AAPhLMAcmHDsHu-0',
    appId: '1:1077071696056:web:bc3802eacea78d4dc4644d',
    messagingSenderId: '1077071696056',
    projectId: 'employeedemoapp-48cb5',
    authDomain: 'employeedemoapp-48cb5.firebaseapp.com',
    storageBucket: 'employeedemoapp-48cb5.appspot.com',
    measurementId: 'G-EB56GFKS7K',
  );
}
